// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[] = "feelon";      // Network SSID (name)
const char PASS[] = "01041531190"; // Network password (use for WPA, or use as key for WEP)

void onSetRGBcolorChange();

CloudColoredLight setRGBcolor;

void initProperties()
{

  ArduinoCloud.addProperty(setRGBcolor, READWRITE, ON_CHANGE, onSetRGBcolorChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
